version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alumni-api
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - alumni-network

  nginx:
    image: nginx:alpine
    container_name: alumni-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - alumni-network

  db:
    image: postgres:16-alpine
    container_name: alumni-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - alumni-network

networks:
  alumni-network:
    driver: bridge

volumes:
  pgdata: